USE [master]
GO

/****** Object:  Database [Banka]    Script Date: 21.10.2022 00:51:28 ******/
CREATE DATABASE [Banka]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Banka', FILENAME = N'C:\Users\aayar\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\Banka.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Banka_log', FILENAME = N'C:\Users\aayar\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\Banka.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Banka].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Banka] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [Banka] SET ANSI_NULLS ON 
GO

ALTER DATABASE [Banka] SET ANSI_PADDING ON 
GO

ALTER DATABASE [Banka] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [Banka] SET ARITHABORT ON 
GO

ALTER DATABASE [Banka] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Banka] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Banka] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Banka] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Banka] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [Banka] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [Banka] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Banka] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [Banka] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Banka] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Banka] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Banka] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Banka] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Banka] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Banka] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Banka] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Banka] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Banka] SET RECOVERY FULL 
GO

ALTER DATABASE [Banka] SET  MULTI_USER 
GO

ALTER DATABASE [Banka] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Banka] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Banka] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Banka] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Banka] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Banka] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Banka] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Banka] SET  READ_WRITE 
GO

